Updated scripts. Now more aggressively stopping execution if something goes wrong. Also updated logic for getting the app asset from the github releases.

diff --git a/stats b/stats
--- a/stats
+++ b/stats
@@ -8,7 +8,13 @@ source env/bin/activate
 python3 -m pip install -r requirements.txt
 
 # Run python script and pass along arguments
-python3 stats_internal.py "$@" 
+python3 stats_internal.py "$@"
+
+# Check the exit status
+if [ $? -ne 0 ]; then
+    echo "stats_internal Python script failed. Exiting."
+    exit 1
+fi
 
 # Deactivate "env"
 deactivate
diff --git a/update b/update
--- a/update
+++ b/update
@@ -16,6 +16,10 @@ git pull;
 # Update appcast files
 echo 'Generating appcasts...'
 python3 ./generate_appcasts;
+if [ $? -ne 0 ]; then
+    echo "generate_appcasts Python script failed. Exiting."
+    exit 1
+fi
 echo 'Pushing new appcasts...'
 git add .;
 git commit -m "Update script: Updated appcasts";
@@ -24,6 +28,10 @@ git push;
 # Record stats
 echo 'Recording stats...'
 ./stats record;
+if [ $? -ne 0 ]; then
+    echo "stats bash script failed. Exiting."
+    exit 1
+fi
 echo 'Pushing new stats...'
 git add .;
 git commit -m "Update script: Recorded stats";
